name: Build and Publish Docker Image

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Convert repository name to lowercase and build the Docker image
      - name: Build Docker image
        run: |
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/${{ github.repository_owner }}/${REPO_NAME}:${{ github.ref_name }} .
          docker tag ghcr.io/${{ github.repository_owner }}/${REPO_NAME}:${{ github.ref_name }} ghcr.io/${{ github.repository_owner }}/${REPO_NAME}:latest

      # Push the Docker image
      - name: Push Docker image
        run: |
          REPO_NAME=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')
          docker push ghcr.io/${{ github.repository_owner }}/${REPO_NAME}:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository_owner }}/${REPO_NAME}:latest
